apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: redhat
          image: redhat/ubi9
          command: ["sleep",  "10"]
      restartPolicy: Never

