apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-09
data:
  URL: google.com
  FQDN: www.google.com
---
apiVersion: v1
kind: pod
metadata:
  name: debug-01
spec:
  containers:
    -name: debug
    image: rkalluru/debug
    env:
      - name: URL
        value: yahoo.com
---
apiVersion: v1
kind: pod
metadata:
  name: debug-cm-01
spec:
  containers:
    -name: debug
    image: rkalluru/debug
envFrom:
  - configMapRef:
      name: cm-09
