apiVersion: v1
kind: Secret
metadata:
  name: secret-10
data:
  URL: Z29vZ2xlLmNvbQ==
  FQDN: d3d3Lmdvb2dsZS5jb20=

---
apiVersion: v1
kind: pod
metadata:
  name: debug-cm-01
spec:
  containers:
    -name: debug-secret-01
    image: rkalluru/debug
envFrom:
  - secretRef:
      name: secret-10
