---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app2

---
apiVersion: v1
kind: Secret
metadata:
  name: app-sec1
data:
  App1_PASSWORD: YWJjZEAxMjM0

---
apiVersion: v1
kind: Secret
metadata:
  name: app-sec2
data:
  App2_PASSWORD: eHl6QDEyMw==
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app1-role
rules:
  - apiGroups: ["v1"]
    resources: ["secrets"]
    resourceNames: ["app-sec1"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app2-role
rules:
  - apiGroups: ["v1"]
    resources: ["secrets"]
    resourceNames: ["app-sec2"]
    verbs: ["get"]
---

---
apiVersion: v1
kind: Secret
metadata:
  name: app-sec2
data:
  App2_PASSWORD: eHl6QDEyMw==
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
rules:
  - apiGroups: ["v1"]
    resources: ["secrets"]
    resourceNames: ["app-sec1"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
    - kind: Group
      name: system:serviceaccounts:app1
      apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app2-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-role
subjects:
  - kind: Group
    name: system:serviceaccounts:app2
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: pod
metadata:
  name: debug-app-01
spec:
  serviceAccountName: app1
  containers:
    -name: debug
    image: rkalluru/debug
envFrom:
  - secretRef:
      name: app-sec1
  - secretRef:
      name: app-sec2
---
apiVersion: v1
kind: pod
metadata:
  name: debug-cm-01
spec:
  serviceAccountName: app2
  containers:
    -name: debug-secret-01
    image: rkalluru/debug
envFrom:
  - secretRef:
      name: app-sec2