apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3  # Choose the volume type: gp2, gp3, io1, etc.
  encrypted: "true"  # Optional: Enable encryption
  iopsPerGB: "10"  # Optional: Set IOPS per GB for provisioned IOPS volumes (e.g., io1 or io2)
  fsType: ext4  # Filesystem type
reclaimPolicy: retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
    - name: debug-container
      image: rkalluru/debug
      volumeMounts:
        - mountPath: /app
          name: app-volume
          volumes:
            - name: app-volume
              persistentVolumeClaim:
                claimName: my-pvc
